title:            Tejbir Wason
description:      Hi! I'm Tejbir Wason. I'm a Junior Software Engineering Student at UBC and this is my blog.
url:              http://www.tejbirwason.com
signoff:          Tej
disqus_shortname: tejbirwason
facebook_appid:   623290107757407
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About Me
    url:          /about
  - name:         Blog
    url:          /
  - name:         Lab
    url:          http://capacious.ca
    external:     true
  - name:         GitHub
    url:          http://github.com/tejbirwason
    external:     true
  - name:         Twitter
    url:          http://twitter.com/tejbirwason
    external:     true
  - name:         LinkedIn
    url:          http://www.linkedin.com/in/tejbirwason
    external:     true
  - name:         Strava
    url:          http://www.strava.com/athletes/tejbirwason
    external:     true
pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
gems: ["emoji_for_jekyll"]