title:            Tejbir Wason
description:      Hi! I'm Tejbir Wason. I'm a Senior Software Engineering Student at UBC and this is my blog.
url:              http://www.tejbirwason.com
signoff:          TJ
disqus_shortname: tejbirwason
facebook_appid:   623290107757407
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         me
    url:          /about
  - name:         blog
    url:          /
  - name:         lab
    url:          http://capacious.ca
  - name:         bookshelf
    url:          https://www.goodreads.com/review/list/13789990-tejbir-wason?shelf=read
  - name:         cv
    url:          /cv
highlighter:      rouge
permalink:        pretty
markdown:         kramdown
redcarpet:
  extensions:
    - smart