title:            Organized Chaos
description:      Tejbir Wason's weblog
url:              # Site url.
signoff:          # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /
  - name:         Email
    url:          mailto:tejbirwason@gmail.com
  - name:         GitHub
    url:          http://github.com/tejbirwason
    external:     true
  - name:         Twitter
    url:          http://twitter.com/tejbirwason
    external:     true
  - name:         LinkedIn
    url:          http://www.linkedin.com/pub/tejbir-wason/30/840/b92
    external:     true
  - name:         Strava
    url:          http://www.strava.com/athletes/tejbirwason
    external:     true
pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart